##########################################################################
# UK THRUST 1B POWER / SAMPLE-SIZE ANALYSIS
# Design-stage event-yield approximation for R0-within
#
# PURPOSE
# -------
# Estimate how many UK OVG participants are likely to need baseline
# screening, and how many pARG-positive participants need to enter the
# controlled antibiotic challenge, to generate sufficient longitudinal
# plasmid-host acquisition information for Thrust 1B.
#
# SCIENTIFIC FRAMEWORK
# --------------------
# The target biological quantity, R0-within, is NOT defined as the number
# of observed events per participant.
#
# Mechanistically, within-gut plasmid spread is expected to depend on:
#
#   beta        = effective in-vivo transfer/acquisition rate
#   D           = donor abundance
#   S           = susceptible-recipient abundance
#   gamma       = plasmid-host loss rate
#   structure   = effective spatial/ecological opportunity for transfer
#   detection   = probability that a true acquisition is resolved
#
# A design-stage branching approximation for the final estimand is:
#
#   R0-within = beta * S_eff * structure_factor / gamma
#
# where S_eff represents susceptible-recipient abundance under the
# specified antibiotic/ecological state.
#
# WHAT THIS POWER SIMULATION DOES
# -------------------------------
# This script does NOT directly estimate beta, D, S, gamma, or R0-within.
#
# Instead, for sample-size planning, the biological acquisition process
#
#   beta x D x S x ecological opportunity
#
# is collapsed into:
#
#   events_per_positive
#
# defined as the expected number of true new plasmid-host acquisition
# events generated by one pARG-positive challenge participant over the
# full observation window.
#
# Thus:
#
#   screened participants
#       -> baseline pARG-positive participants
#       -> pARG-positive challenge participants
#       -> true acquisition events
#       -> detected acquisition events
#       -> approximate information / precision
#
# True acquisition events are simulated using a Poisson approximation,
# and each true event is subsequently observed with probability
# detection_probability.
#
# PRECISION APPROXIMATION
# -----------------------
# For design purposes, this script uses:
#
#   relative_precision ~= 1.96 / sqrt(number of detected events)
#
# as a simple event-count information approximation.
#
# Therefore, the variable currently labelled probability_R0_precision_50
# should be interpreted as the probability of obtaining enough detected
# acquisition events to satisfy the design-stage 50% precision proxy.
#
# It is NOT yet the simulated confidence-interval precision of an
# estimated R0-within.
#
# INTERPRETATION
# --------------
# This analysis is intended to answer:
#
#   1. How many randomly selected participants need to be screened?
#   2. How many pARG-positive participants are likely to be available
#      for controlled antibiotic challenge?
#   3. Under plausible acquisition and detection rates, how many resolved
#      plasmid-host acquisition events are likely to be observed?
#   4. Is that event yield sufficient to support the planned mechanistic
#      analysis?
#
# FINAL LEAP ANALYSIS
# -------------------
# This is a DESIGN-STAGE POWER / FEASIBILITY SIMULATION, not the final
# Wellcome Leap estimator.
#
# The final longitudinal analysis will estimate within-gut plasmid
# transmission mechanistically from the observed plasmid-host data,
# including acquisition, susceptible-cell opportunity, antibiotic state,
# persistence/loss, and relevant participant-level/ecological structure.
#
# The final R0-within estimate will therefore be derived from the
# pre-specified longitudinal mechanistic model rather than from
# events_per_positive or the simple event-count precision approximation
# used here.
##########################################################################

##########################################################################
# 1. STUDY DESIGN
##########################################################################

rm(list = ls())
set.seed(2026)

library(dplyr)
library(writexl)

# 1. STUDY DESIGN

screened_grid <- c(
  100, 150, 200, 300, 400, 500, 600, 800, 1000
)

challenge_grid <- c(
  25, 50, 75, 100, 150, 200
)

numsims <- 100

# Samples around the controlled antibiotic challenge
challenge_times <- c(
  0, 3, 7, 14, 28
)

# Approximate resolved Enterobacterales cells per sample
cells_per_sample <- 1000

# Leap precision targets
R0_precision_target <- 0.50
parameter_precision_target <- 0.30
power_target <- 0.80

# 2. BASELINE PREVALENCE SCENARIOS

# This is the prevalence in the RANDOMLY SELECTED population invited to
# baseline screening.
#
baseline_prevalence_grid <- c(
  0.05,
  0.10,
  0.15,
  0.20,
  0.30
)

# 3. HUMAN-CHALLENGE DESIGN

# Fraction of baseline-screened eligible pARG-positive participants who
# agree / qualify for challenge.
#
challenge_enrolment_probability_grid <- c(
  0.50,
  0.75,
  0.90
)

# Expected true new plasmid-to-new-host acquisition events per pARG-positive
# challenge participant over the full challenge observation window.
#
# This is the key biological uncertainty.
#
events_per_positive_grid <- c(
  0.10,
  0.25,
  0.50,
  1.00
)

# Probability that a true acquisition is actually resolved as a new
# plasmid-host background.
#
detection_probability_grid <- c(
  0.40,
  0.70,
  0.90
)

# 4. EVENT-COUNT PRECISION

calculate_precision <- function(n_events) {
  if (n_events < 5) {
    return(NA_real_)
  }
  
  1.96 / sqrt(n_events)
}

events_needed_50 <- ceiling(
  (1.96 / R0_precision_target)^2
)

events_needed_30 <- ceiling(
  (1.96 / parameter_precision_target)^2
)

# 5. SIMULATE ONE STUDY

simulate_study <- function(
    n_screened,
    baseline_prevalence,
    challenge_enrolment_probability,
    n_challenge_target,
    events_per_positive,
    detection_probability
) {
  
  # Randomly selected population
  #
  baseline_positive <- rbinom(
    n = n_screened,
    size = 1,
    prob = baseline_prevalence
  )
  
  n_baseline_positive <- sum(
    baseline_positive
  )
  
  # Among baseline-positive people, determine who enters the challenge
  #
  eligible_for_challenge <- which(
    baseline_positive == 1
  )
  
  if (length(eligible_for_challenge) > 0) {
    
    invited_to_challenge <- rbinom(
      n = length(eligible_for_challenge),
      size = 1,
      prob = challenge_enrolment_probability
    )
    
    challenge_positive_ids <- eligible_for_challenge[
      invited_to_challenge == 1
    ]
    
  } else {
    
    challenge_positive_ids <- integer(0)
    
  }
  
  # Number of pARG-positive participants actually available for challenge
  #
  n_available_positive <- length(
    challenge_positive_ids
  )
  
  # If we have more eligible positive participants than the intended
  # challenge size, randomly select the required number.
  #
  n_positive_challenge <- min(
    n_available_positive,
    n_challenge_target
  )
  
  if (n_positive_challenge > 0) {
    
    selected_positive <- sample(
      challenge_positive_ids,
      n_positive_challenge
    )
    
  } else {
    
    selected_positive <- integer(0)
    
  }
  
  # Optional negative reference component.
  #
  # Here we assume approximately 25% of the challenge cohort is drawn from
  # baseline-negative participants for calibration/reference purposes.
  #
  n_negative_target <- floor(
    n_challenge_target * 0.25
  )
  
  eligible_negative <- which(
    baseline_positive == 0
  )
  
  n_negative_challenge <- min(
    length(eligible_negative),
    n_negative_target
  )
  
  # Total challenge cohort achieved
  #
  n_challenge_achieved <- (
    n_positive_challenge +
      n_negative_challenge
  )
  
  # True acquisition events come from pARG-positive challenge participants
  #
  true_events <- if (
    n_positive_challenge > 0
  ) {
    
    sum(
      rpois(
        n = n_positive_challenge,
        lambda = events_per_positive
      )
    )
    
  } else {
    
    0
    
  }
  
  # Observed acquisition events
  #
  detected_events <- if (
    true_events > 0
  ) {
    
    rbinom(
      n = 1,
      size = true_events,
      prob = detection_probability
    )
    
  } else {
    
    0
    
  }
  
  # Approximate precision
  #
  relative_precision <- calculate_precision(
    detected_events
  )
  
  # Intensive sampling burden
  #
  intensive_samples <- (
    n_challenge_achieved *
      length(challenge_times)
  )
  
  total_cells_profiled <- (
    intensive_samples *
      cells_per_sample
  )
  
  data.frame(
    n_screened = n_screened,
    baseline_prevalence = baseline_prevalence,
    challenge_enrolment_probability =
      challenge_enrolment_probability,
    n_baseline_positive =
      n_baseline_positive,
    n_available_positive =
      n_available_positive,
    n_positive_challenge =
      n_positive_challenge,
    n_negative_challenge =
      n_negative_challenge,
    n_challenge_achieved =
      n_challenge_achieved,
    true_events =
      true_events,
    detected_events =
      detected_events,
    relative_precision =
      relative_precision,
    meets_R0_50 =
      !is.na(relative_precision) &
      relative_precision <= R0_precision_target,
    intensive_samples =
      intensive_samples,
    total_cells_profiled =
      total_cells_profiled
  )
}

# 6. PRIMARY SCENARIO

primary_prevalence <- 0.10
primary_challenge_enrolment <- 0.75
primary_challenge_target <- 100
primary_events_per_positive <- 0.50
primary_detection_probability <- 0.70

# 7. PRIMARY SCREENING REQUIREMENT

primary_screen_results <- list()
row_id <- 1

for (n_screened in screened_grid) {
  
  for (sim in seq_len(numsims)) {
    
    primary_screen_results[[row_id]] <-
      simulate_study(
        n_screened =
          n_screened,
        baseline_prevalence =
          primary_prevalence,
        challenge_enrolment_probability =
          primary_challenge_enrolment,
        n_challenge_target =
          primary_challenge_target,
        events_per_positive =
          primary_events_per_positive,
        detection_probability =
          primary_detection_probability
      )
    
    row_id <- row_id + 1
  }
}

primary_screen_results <- do.call(
  rbind,
  primary_screen_results
)

# 8. PRIMARY SUMMARY

primary_summary <- primary_screen_results %>%
  group_by(
    n_screened
  ) %>%
  summarise(
    mean_baseline_positive =
      mean(n_baseline_positive),
    mean_positive_available_for_challenge =
      mean(n_available_positive),
    probability_achieve_50_positive_challenge =
      mean(n_positive_challenge >= 50),
    probability_achieve_75_positive_challenge =
      mean(n_positive_challenge >= 75),
    probability_achieve_100_positive_challenge =
      mean(n_positive_challenge >= 100),
    mean_positive_challenge =
      mean(n_positive_challenge),
    mean_detected_events =
      mean(detected_events),
    probability_16_detected_events =
      mean(detected_events >= events_needed_50),
    probability_40_detected_events =
      mean(detected_events >= events_needed_30),
    probability_R0_precision_50 =
      mean(meets_R0_50),
    .groups = "drop"
  )

# 9. CHALLENGE-COHORT VIEW

challenge_summary <- primary_screen_results %>%
  group_by(
    n_screened
  ) %>%
  summarise(
    mean_positive_challenge =
      mean(n_positive_challenge),
    mean_negative_reference =
      mean(n_negative_challenge),
    mean_total_challenge =
      mean(n_challenge_achieved),
    mean_detected_events =
      mean(detected_events),
    mean_intensive_samples =
      mean(intensive_samples),
    mean_cells_profiled =
      mean(total_cells_profiled),
    probability_R0_precision_50 =
      mean(meets_R0_50),
    .groups = "drop"
  )

# 10. FULL SENSITIVITY ANALYSIS

sensitivity_results <- list()
row_id <- 1

for (prev in baseline_prevalence_grid) {
  
  for (enrolment in challenge_enrolment_probability_grid) {
    
    for (events in events_per_positive_grid) {
      
      for (detect in detection_probability_grid) {
        
        for (n_screened in screened_grid) {
          
          sims <- vector(
            "list",
            numsims
          )
          
          for (sim in seq_len(numsims)) {
            
            sims[[sim]] <- simulate_study(
              n_screened =
                n_screened,
              baseline_prevalence =
                prev,
              challenge_enrolment_probability =
                enrolment,
              n_challenge_target =
                primary_challenge_target,
              events_per_positive =
                events,
              detection_probability =
                detect
            )
          }
          
          d <- do.call(
            rbind,
            sims
          )
          
          sensitivity_results[[row_id]] <-
            data.frame(
              baseline_prevalence =
                prev,
              challenge_enrolment_probability =
                enrolment,
              events_per_positive =
                events,
              detection_probability =
                detect,
              n_screened =
                n_screened,
              mean_baseline_positive =
                mean(d$n_baseline_positive),
              mean_positive_challenge =
                mean(d$n_positive_challenge),
              mean_detected_events =
                mean(d$detected_events),
              probability_16_events =
                mean(
                  d$detected_events >=
                    events_needed_50
                ),
              probability_40_events =
                mean(
                  d$detected_events >=
                    events_needed_30
                ),
              probability_R0_precision_50 =
                mean(d$meets_R0_50)
            )
          
          row_id <- row_id + 1
        }
      }
    }
  }
}

sensitivity_results <- do.call(
  rbind,
  sensitivity_results
)

# 11. MEETING TABLE:
# HOW MANY PEOPLE NEED TO BE SCREENED TO OBTAIN THE DESIRED NUMBER
# OF PARG-POSITIVE CHALLENGE PARTICIPANTS?

screening_table <- sensitivity_results %>%
  filter(
    challenge_enrolment_probability ==
      primary_challenge_enrolment,
    events_per_positive ==
      primary_events_per_positive,
    detection_probability ==
      primary_detection_probability
  ) %>%
  mutate(
    probability_50_positive =
      probability_16_events * 0 +
      NA_real_
  ) %>%
  select(
    baseline_prevalence,
    n_screened,
    mean_baseline_positive,
    mean_positive_challenge,
    probability_16_events,
    probability_R0_precision_50
  )

# 12. MINIMUM SCREENED N FOR 80% PROBABILITY OF OBTAINING
# SPECIFIED NUMBERS OF POSITIVE CHALLENGE PARTICIPANTS

challenge_yield_table <- sensitivity_results %>%
  filter(
    challenge_enrolment_probability ==
      primary_challenge_enrolment
  ) %>%
  group_by(
    baseline_prevalence
  ) %>%
  summarise(
    minimum_N_for_50_positive_challenge =
      ifelse(
        any(
          mean_positive_challenge >= 50
        ),
        min(
          n_screened[
            mean_positive_challenge >= 50
          ]
        ),
        NA_real_
      ),
    minimum_N_for_75_positive_challenge =
      ifelse(
        any(
          mean_positive_challenge >= 75
        ),
        min(
          n_screened[
            mean_positive_challenge >= 75
          ]
        ),
        NA_real_
      ),
    minimum_N_for_100_positive_challenge =
      ifelse(
        any(
          mean_positive_challenge >= 100
        ),
        min(
          n_screened[
            mean_positive_challenge >= 100
          ]
        ),
        NA_real_
      ),
    .groups = "drop"
  )

# 13. PARAMETER TABLE

parameter_dictionary <- data.frame(
  parameter = c(
    "n_screened",
    "baseline_prevalence",
    "challenge_enrolment_probability",
    "n_positive_challenge",
    "events_per_positive",
    "detection_probability",
    "detected_events",
    "R0_within"
  ),
  meaning = c(
    "Randomly selected participants screened before challenge",
    "Pre-challenge prevalence of the focal pARG in the source population",
    "Probability that an eligible pARG-positive participant enters the challenge cohort",
    "Number of pARG-positive participants actually receiving the controlled antibiotic challenge",
    "Design-stage expected true new plasmid-host acquisitions per pARG-positive challenge participant",
    "Probability that a true acquisition is resolved",
    "Observed new plasmid-host acquisition events",
    "Final Leap estimand derived from acquisition per susceptible cells and pARG loss"
  ),
  interpretation = c(
    "Determines how many people need to be screened",
    "Key baseline empirical quantity",
    "Recruitment/eligibility parameter",
    "Main informative human-challenge population",
    "Key biological uncertainty",
    "Laboratory measurement parameter",
    "Primary information source for 1B",
    "Final mechanistic outcome"
  )
)

# 14. ASSUMPTIONS TABLE

assumptions <- data.frame(
  parameter = c(
    "screened_grid",
    "challenge_grid",
    "number_simulations",
    "challenge_sampling_days",
    "cells_per_sample",
    "primary_baseline_prevalence",
    "primary_challenge_enrolment",
    "primary_challenge_target",
    "primary_events_per_positive",
    "primary_detection_probability",
    "R0_precision_target",
    "parameter_precision_target",
    "power_target",
    "approx_events_for_50pct_precision",
    "approx_events_for_30pct_precision"
  ),
  value = c(
    paste(
      screened_grid,
      collapse = ", "
    ),
    paste(
      challenge_grid,
      collapse = ", "
    ),
    numsims,
    paste(
      challenge_times,
      collapse = ", "
    ),
    cells_per_sample,
    primary_prevalence,
    primary_challenge_enrolment,
    primary_challenge_target,
    primary_events_per_positive,
    primary_detection_probability,
    R0_precision_target,
    parameter_precision_target,
    power_target,
    events_needed_50,
    events_needed_30
  )
)

# 15. SAVE

output_dir <- "./Output"

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}

write_xlsx(
  list(
    Assumptions =
      assumptions,
    ParameterDictionary =
      parameter_dictionary,
    PrimarySummary =
      primary_summary,
    ChallengeSummary =
      challenge_summary,
    ScreeningTable =
      screening_table,
    ChallengeYield =
      challenge_yield_table,
    Sensitivity =
      sensitivity_results
  ),
  file.path(
    "./Output/Thrust1b/UK_Thrust1B_simple_R0within_sample_size.xlsx"
  )
)

print(primary_summary, row.names = FALSE)
print(challenge_yield_table, row.names = FALSE)